---
  - name: Include OS-specific variables.
    include_vars: "{{ ansible_os_family }}.yml"

  - name: NETDATA | Check if present
    stat:
      path: "{{ netdata_binary }}"
    register: netdata_present
  - debug: msg="netdata not installed"
    when: netdata_present.stat.exists == False
  - debug: msg="netdata installed"
    when: netdata_present.stat.exists == True

  - name: NETDATA | Install package dependencies
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ netdata_deps }}"
    when: netdata_present.stat.exists == False
    become: yes

  - name: NETDATA | Clone or Pull for Install or Update
    git:
      repo: https://github.com/firehol/netdata.git
      dest: "{{ netdata_install_dir }}"
      depth: 1
      version: "{{ netdata_version }}"
    register: clone_or_pull

  - debug: var=clone_or_pull

  - name: NETDATA | Build and install
    shell: "./netdata-installer.sh --install {{ netdata_install_dir }} --dont-wait"
    args:
      chdir: "{{ netdata_install_dir }}"
    when: clone_or_pull.changed == True
    become: yes

    notify: stop service

  - meta: flush_handlers

  - name: copy service file
    command: cp {{ netdata_install_dir }}/system/netdata.service /etc/systemd/system/netdata.service
    when: clone_or_pull.changed == True and ansible_service_mgr == "systemd"
    notify: start and enable systemd

  - name: copy service file
    command: cp {{ netdata_install_dir }}/system/netdata-lsb /etc/init.d/netdata
    when: clone_or_pull.changed == True and ansible_service_mgr == "init"
    notify: start and enable service
